# Generated by Django 4.0.5 on 2023-05-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
