# Generated by Django 4.0.5 on 2023-05-16 09:20

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_userpost_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmedia',
            name='media_file',
            field=models.FileField(upload_to=content.models.PostMedia.get_media_url),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='caption',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
