# Generated by Django 4.0.5 on 2023-05-16 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_networkedge_unique_together'),
        ('content', '0004_postlikes_postcomments'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postlikes',
            unique_together={('post', 'liked_by')},
        ),
    ]
